### ISSUE TITLE
Incluir campo IBGE no retorno

### ISSUE THREAD

**Issue by tfiliano** [Webschool-io/CEP-Be-MEAN#1]
Seria muito útil nas consultas BR, trazer também o código IBGE das cidades.

**Comment by higordiego** [comment]
Olá, estamos atualizando o sistema para retornar o ibge..


Vlw pelo o feedback.

**Comment by souzacristsf** [comment]
Modificação realizada conforme analisado. 
Incluso campo IBGE no retorno do JSON.
